trigger:
    - main-temp

pr: none

pool:
    name: Hosted Ubuntu 1604

steps:
    - task: UseNode@1
      inputs:
          version: "10.15.3"

    - script: |
          cd ./static/admin/
          sed -i 's/zzzbranchzzz/master/g' config.yml
      displayName: "Edit config.yml"

    - script: |
          npm install
          npm run build
      displayName: "Npm install and build"

    - task: CopyFiles@2
      displayName: "Copy generated content"
      inputs:
          SourceFolder: "$(Build.SourcesDirectory)/public"
          contents: "**/*"
          targetFolder: "$(Build.ArtifactStagingDirectory)/public"
          cleanTargetFolder: true

    - task: CopyFiles@2
      displayName: "Copy arm template for production"
      inputs:
          SourceFolder: "$(Build.SourcesDirectory)"
          contents: "deploy-prod.json"
          targetFolder: "$(Build.ArtifactStagingDirectory)"
          cleanTargetFolder: false

    - task: CopyFiles@2
      displayName: "Copy Post Release Job script"
      inputs:
          SourceFolder: "$(Build.SourcesDirectory)/post-release-job"
          contents: "*"
          targetFolder: "$(Build.ArtifactStagingDirectory)/post-release-job"
          cleanTargetFolder: false

    - task: PublishBuildArtifacts@1
      displayName: "Publish Artifact"
      inputs:
          PathtoPublish: "$(build.artifactstagingdirectory)"
