backend:
    name: github
    repo: dibkunnskap/bompengekalkulator-landingsside
media_folder: static/img
public_folder: /img
collections:
    - name: "blog"
      label: "Blogg"
      folder: "src/pages/blogg"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Publish Date", name: "date", widget: "datetime"}
        - {label: "Description", name: "description", widget: "text"}
        - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
        - {label: "Body", name: "body", widget: "markdown"}

    - name: "pages"
      label: "Pages"
      files:
          - file: "src/pages/index.md"
            label: "Front page"
            name: "index"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "index-page",
                  }
                - {label: Header, name: heading, widget: string}
                - {label: Bilde, name: image, widget: image}
                - {label: Hovedtekst, name: mainText, widget: markdown}
                - {label: Tekst, name: secondaryText, widget: markdown}
                - {
                      label: Features,
                      name: features,
                      widget: object,
                      fields:
                          [
                              {
                                  label: Blurbs,
                                  name: blurbs,
                                  widget: list,
                                  fields:
                                      [
                                          {
                                              label: Image,
                                              name: image,
                                              widget: image,
                                          },
                                          {
                                              label: Heading,
                                              name: heading,
                                              widget: string,
                                          },
                                          {
                                              label: Text,
                                              name: text,
                                              widget: text,
                                          },
                                      ],
                              },
                          ],
                  }
          - file: "src/pages/integrasjon/index.md"
            label: "Integrasjon"
            name: "integrasjon"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "integrasjon-page",
                  }
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Body", name: "body", widget: "markdown"}
          - file: "src/pages/apper/index.md"
            label: "Apps"
            name: "apps"
            fields:
                - {
                      label: "Template Key",
                      name: "templateKey",
                      widget: "hidden",
                      default: "app-page",
                  }
                - {label: "Title", name: "title", widget: "string"}
                - {label: "Beskrivelse", name: "description", widget: "string"}
                - {
                      label: Applikasjoner,
                      name: apps,
                      widget: list,
                      fields:
                          [
                              {label: Image, name: image, widget: image},
                              {label: Heading, name: heading, widget: string},
                              {label: Text, name: text, widget: markdown},
                          ],
                  }
